spring.application.name=workspace
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/workspace_service?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=workspace_user
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jackson.time-zone=Asia/Ho_Chi_Minh

identity.service.url=http://localhost:8081